# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Venv_projects/tdv/app/package/tdv_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_TDV(object):
    def setupUi(self, main_TDV):
        main_TDV.setObjectName("main_TDV")
        main_TDV.resize(1920, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_TDV.sizePolicy().hasHeightForWidth())
        main_TDV.setSizePolicy(sizePolicy)
        main_TDV.setMinimumSize(QtCore.QSize(580, 750))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Users/90531/Desktop/indir.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_TDV.setWindowIcon(icon)
        main_TDV.setAutoFillBackground(False)
        main_TDV.setStyleSheet("")
        main_TDV.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        main_TDV.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(main_TDV)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("font-size:18px;\n"
"background-color:rgba(32,36,66,1)")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 36, 66))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("border:none;font-size:25px; color:#fff")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.kontrol = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.kontrol.setPalette(palette)
        self.kontrol.setStyleSheet("background:transparent;")
        self.kontrol.setObjectName("kontrol")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.kontrol)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 1311, 1041))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1311, 651))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.layout_Video = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.layout_Video.setContentsMargins(0, 0, 0, 0)
        self.layout_Video.setObjectName("layout_Video")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(690, 660, 601, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.widget_4)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 90, 581, 211))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_13.setStyleSheet("color:white;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setStyleSheet("color:white;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setStyleSheet("color:white;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_16.setStyleSheet("color:white;")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lbl_pharmacyName = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_pharmacyName.setStyleSheet("color:white;")
        self.lbl_pharmacyName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pharmacyName.setObjectName("lbl_pharmacyName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_pharmacyName)
        self.lbl_pharmacyDist = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_pharmacyDist.setStyleSheet("color:white;")
        self.lbl_pharmacyDist.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pharmacyDist.setObjectName("lbl_pharmacyDist")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_pharmacyDist)
        self.lbl_pharmacyAddress = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_pharmacyAddress.setStyleSheet("color:white;font-size:15px;")
        self.lbl_pharmacyAddress.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pharmacyAddress.setObjectName("lbl_pharmacyAddress")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_pharmacyAddress)
        self.lbl_pharmacyPhone = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lbl_pharmacyPhone.setStyleSheet("color:white;")
        self.lbl_pharmacyPhone.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pharmacyPhone.setObjectName("lbl_pharmacyPhone")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_pharmacyPhone)
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        self.label_19.setGeometry(QtCore.QRect(70, 20, 441, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setStyleSheet("font-size:35px;color:white;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(10, 660, 661, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.lbl_verse = QtWidgets.QLabel(self.widget_5)
        self.lbl_verse.setGeometry(QtCore.QRect(10, 10, 641, 301))
        self.lbl_verse.setStyleSheet("font-size:25px;color:white;")
        self.lbl_verse.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_verse.setWordWrap(True)
        self.lbl_verse.setObjectName("lbl_verse")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(800, 1000, 291, 41))
        self.label_17.setStyleSheet("font-size:20px;\n"
"color:white;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.btn_ext = QtWidgets.QPushButton(self.widget)
        self.btn_ext.setGeometry(QtCore.QRect(10, 990, 151, 31))
        self.btn_ext.setStyleSheet("font-size:20px;\n"
"color:rgba(185,185,185, 0.8);")
        self.btn_ext.setObjectName("btn_ext")
        self.lbl_EcgIcon = QtWidgets.QLabel(self.widget)
        self.lbl_EcgIcon.setGeometry(QtCore.QRect(850, 990, 51, 51))
        self.lbl_EcgIcon.setText("")
        self.lbl_EcgIcon.setScaledContents(True)
        self.lbl_EcgIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_EcgIcon.setObjectName("lbl_EcgIcon")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.widget_2 = QtWidgets.QWidget(self.kontrol)
        self.widget_2.setGeometry(QtCore.QRect(1330, 100, 571, 491))
        self.widget_2.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(50, 0, 491, 41))
        self.label.setStyleSheet("font-size:20px;color:white;border:none;\n"
"border-radius: 45px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(320, 150, 181, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("color:white;font-size:15px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("color:white;font-size:15px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("color:white;font-size:15px;")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lbl_minDegree = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_minDegree.setStyleSheet("color:white;font-size:15px;")
        self.lbl_minDegree.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_minDegree.setObjectName("lbl_minDegree")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_minDegree)
        self.lbl_maxDegree = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_maxDegree.setStyleSheet("color:white;font-size:15px;")
        self.lbl_maxDegree.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_maxDegree.setObjectName("lbl_maxDegree")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_maxDegree)
        self.lbl_degree = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_degree.setStyleSheet("color:white;font-size:15px;")
        self.lbl_degree.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_degree.setObjectName("lbl_degree")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_degree)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("color:white;font-size:15px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lbl_humidity = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_humidity.setStyleSheet("color:white;font-size:15px;")
        self.lbl_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_humidity.setObjectName("lbl_humidity")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_humidity)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 40, 291, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_weatherDescription = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_weatherDescription.setStyleSheet("color:white;font-size:15px;")
        self.lbl_weatherDescription.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_weatherDescription.setObjectName("lbl_weatherDescription")
        self.verticalLayout_3.addWidget(self.lbl_weatherDescription)
        self.lbl_day = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_day.setStyleSheet("color:white;font-size:15px;")
        self.lbl_day.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_day.setObjectName("lbl_day")
        self.verticalLayout_3.addWidget(self.lbl_day)
        self.lbl_date = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_date.setStyleSheet("color:white;font-size:15px;")
        self.lbl_date.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout_3.addWidget(self.lbl_date)
        self.lbl_WeatherIcon = QtWidgets.QLabel(self.widget_2)
        self.lbl_WeatherIcon.setGeometry(QtCore.QRect(40, 80, 181, 171))
        self.lbl_WeatherIcon.setText("")
        self.lbl_WeatherIcon.setScaledContents(True)
        self.lbl_WeatherIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_WeatherIcon.setObjectName("lbl_WeatherIcon")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 290, 521, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setStyleSheet("font-size:20px;color:white;border:none;\n"
"border-radius: 45px;\n"
"")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.lbl_dict_title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_dict_title.setStyleSheet("color:white;font-size:15px;")
        self.lbl_dict_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dict_title.setObjectName("lbl_dict_title")
        self.verticalLayout_4.addWidget(self.lbl_dict_title)
        self.lbl_dict_explain = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lbl_dict_explain.setStyleSheet("color:white;font-size:15px;")
        self.lbl_dict_explain.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_dict_explain.setObjectName("lbl_dict_explain")
        self.verticalLayout_4.addWidget(self.lbl_dict_explain)
        self.widget_3 = QtWidgets.QWidget(self.kontrol)
        self.widget_3.setGeometry(QtCore.QRect(1330, 600, 571, 321))
        self.widget_3.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.widget_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 90, 521, 228))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lbl_imsak = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_imsak.setStyleSheet("color:white;")
        self.lbl_imsak.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_imsak.setObjectName("lbl_imsak")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_imsak)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lbl_sun = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_sun.setStyleSheet("color:white;")
        self.lbl_sun.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sun.setObjectName("lbl_sun")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_sun)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setStyleSheet("color:white;")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lbl_noon = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_noon.setStyleSheet("color:white;")
        self.lbl_noon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_noon.setObjectName("lbl_noon")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_noon)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lbl_afternoon = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_afternoon.setStyleSheet("color:white;")
        self.lbl_afternoon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_afternoon.setObjectName("lbl_afternoon")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_afternoon)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setStyleSheet("color:white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lbl_evening = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_evening.setStyleSheet("color:white;")
        self.lbl_evening.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_evening.setObjectName("lbl_evening")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lbl_evening)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setStyleSheet("color:white;")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lbl_night = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.lbl_night.setStyleSheet("color:white;")
        self.lbl_night.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_night.setObjectName("lbl_night")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lbl_night)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setGeometry(QtCore.QRect(70, 20, 441, 61))
        self.label_12.setStyleSheet("font-size:35px;color:white;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.widget_6 = QtWidgets.QWidget(self.kontrol)
        self.widget_6.setGeometry(QtCore.QRect(1330, 0, 571, 91))
        self.widget_6.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.lbl_time = QtWidgets.QLabel(self.widget_6)
        self.lbl_time.setGeometry(QtCore.QRect(120, 10, 331, 71))
        self.lbl_time.setStyleSheet("font-size:35px;color:white;border:none;\n"
"border-radius: 45px;\n"
"")
        self.lbl_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_time.setObjectName("lbl_time")
        self.lbl_FlagIcon = QtWidgets.QLabel(self.widget_6)
        self.lbl_FlagIcon.setGeometry(QtCore.QRect(460, 10, 91, 71))
        self.lbl_FlagIcon.setText("")
        self.lbl_FlagIcon.setScaledContents(True)
        self.lbl_FlagIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_FlagIcon.setObjectName("lbl_FlagIcon")
        self.lbl_TdvIcon = QtWidgets.QLabel(self.widget_6)
        self.lbl_TdvIcon.setGeometry(QtCore.QRect(30, 10, 81, 71))
        self.lbl_TdvIcon.setText("")
        self.lbl_TdvIcon.setScaledContents(True)
        self.lbl_TdvIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_TdvIcon.setObjectName("lbl_TdvIcon")
        self.widget_7 = QtWidgets.QWidget(self.kontrol)
        self.widget_7.setGeometry(QtCore.QRect(1550, 930, 161, 131))
        self.widget_7.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.lbl_QRIcon2 = QtWidgets.QLabel(self.widget_7)
        self.lbl_QRIcon2.setGeometry(QtCore.QRect(20, 10, 121, 111))
        self.lbl_QRIcon2.setText("")
        self.lbl_QRIcon2.setScaledContents(True)
        self.lbl_QRIcon2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_QRIcon2.setObjectName("lbl_QRIcon2")
        self.widget_8 = QtWidgets.QWidget(self.kontrol)
        self.widget_8.setGeometry(QtCore.QRect(1350, 930, 161, 131))
        self.widget_8.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_8.setObjectName("widget_8")
        self.lbl_QRIcon1 = QtWidgets.QLabel(self.widget_8)
        self.lbl_QRIcon1.setGeometry(QtCore.QRect(20, 10, 121, 111))
        self.lbl_QRIcon1.setText("")
        self.lbl_QRIcon1.setScaledContents(True)
        self.lbl_QRIcon1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_QRIcon1.setObjectName("lbl_QRIcon1")
        self.widget_9 = QtWidgets.QWidget(self.kontrol)
        self.widget_9.setGeometry(QtCore.QRect(1730, 930, 161, 131))
        self.widget_9.setStyleSheet("background-color:rgba(45,50,90, 0.8);\n"
"border:none;\n"
"border-radius: 45px;\n"
"")
        self.widget_9.setObjectName("widget_9")
        self.lbl_QRIcon3 = QtWidgets.QLabel(self.widget_9)
        self.lbl_QRIcon3.setGeometry(QtCore.QRect(20, 10, 121, 111))
        self.lbl_QRIcon3.setText("")
        self.lbl_QRIcon3.setScaledContents(True)
        self.lbl_QRIcon3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_QRIcon3.setObjectName("lbl_QRIcon3")
        self.tabWidget.addTab(self.kontrol, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        main_TDV.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(main_TDV)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(main_TDV)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_TDV)

    def retranslateUi(self, main_TDV):
        _translate = QtCore.QCoreApplication.translate
        main_TDV.setWindowTitle(_translate("main_TDV", "TDV KARABUK"))
        self.label_13.setText(_translate("main_TDV", " İSİM :"))
        self.label_14.setText(_translate("main_TDV", "MEVKİ :"))
        self.label_15.setText(_translate("main_TDV", "ADRES :"))
        self.label_16.setText(_translate("main_TDV", "TELEFON :"))
        self.lbl_pharmacyName.setText(_translate("main_TDV", "NONE"))
        self.lbl_pharmacyDist.setText(_translate("main_TDV", "NONE"))
        self.lbl_pharmacyAddress.setText(_translate("main_TDV", "NONE"))
        self.lbl_pharmacyPhone.setText(_translate("main_TDV", "NONE"))
        self.label_19.setText(_translate("main_TDV", "NÖBETÇİ ECZANE"))
        self.lbl_verse.setText(_translate("main_TDV", "NONE"))
        self.label_17.setText(_translate("main_TDV", "MILITEK"))
        self.btn_ext.setText(_translate("main_TDV", "Kapat"))
        self.label.setText(_translate("main_TDV", "HAVA DURUMU"))
        self.label_2.setText(_translate("main_TDV", "SICAKLIK : "))
        self.label_4.setText(_translate("main_TDV", "EN DÜŞÜK :"))
        self.label_5.setText(_translate("main_TDV", "EN YÜKSEK :"))
        self.lbl_minDegree.setText(_translate("main_TDV", "0 °"))
        self.lbl_maxDegree.setText(_translate("main_TDV", "0°"))
        self.lbl_degree.setText(_translate("main_TDV", "0 °"))
        self.label_6.setText(_translate("main_TDV", "NEM ORANI :"))
        self.lbl_humidity.setText(_translate("main_TDV", "0"))
        self.lbl_weatherDescription.setText(_translate("main_TDV", "Güneşli"))
        self.lbl_day.setText(_translate("main_TDV", "Pazartesi"))
        self.lbl_date.setText(_translate("main_TDV", "04.09.2003"))
        self.label_18.setText(_translate("main_TDV", "SÖZLÜK"))
        self.lbl_dict_title.setText(_translate("main_TDV", "WORD"))
        self.lbl_dict_explain.setText(_translate("main_TDV", "NONE"))
        self.label_3.setText(_translate("main_TDV", "İMSAK :"))
        self.lbl_imsak.setText(_translate("main_TDV", "0"))
        self.label_7.setText(_translate("main_TDV", "GÜNEŞ :"))
        self.lbl_sun.setText(_translate("main_TDV", "0"))
        self.label_8.setText(_translate("main_TDV", "ÖĞLE :"))
        self.lbl_noon.setText(_translate("main_TDV", "0"))
        self.label_9.setText(_translate("main_TDV", "İKİNDİ :"))
        self.lbl_afternoon.setText(_translate("main_TDV", "0"))
        self.label_10.setText(_translate("main_TDV", "AKŞAM :"))
        self.lbl_evening.setText(_translate("main_TDV", "0"))
        self.label_11.setText(_translate("main_TDV", "YATSI :"))
        self.lbl_night.setText(_translate("main_TDV", "0"))
        self.label_12.setText(_translate("main_TDV", "EZAN VAKİTLERİ"))
        self.lbl_time.setText(_translate("main_TDV", "SAAT : 0:0:0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kontrol), _translate("main_TDV", "Kontrol"))
        self.actionExit.setText(_translate("main_TDV", "Exit"))

